version: '3.8'
services:
  x-ui:
    image: enwaiax/x-ui
    container_name: x-ui
    volumes:
      - xui-db:/etc/x-ui/
      - xui-cert:/root/cert/
    restart: unless-stopped
    network_mode: host
volumes:
  xui-db:
  xui-cert:
