version: "3.3"
services:
  alist:
    image: "xhofe/alist:latest"
    restart: unless-stopped
    container_name: alist
    volumes:
      - alist-data:/opt/alist/data'
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022

volumes:
  alist-data:
