version: "3.8"

services:
  cloudflared:
    restart: always
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./openssl:/etc/nginx/certs # Mount the certificates directory
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data:
  letsencrypt:
