version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    restart: on-failure
    volumes:
      - redis-data:/data
    ports:
      - 8001:8001
      - 6379:6379

volumes:
  redis-data: