version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin_postgre
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
