version: "3.8"
services:
  typesence:
    image: typesense/typesense:0.25.0
    ports:
      - "8108:8108"
      - "8107:8107"
    volumes:
      - typesence-data:/data
    command:
      [
        "--data-dir",
        "/data",
        "--api-key=xyz",
        "--listen-port=8108",
        "--enable-cors",
        "--enable-metrics",
      ]
volumes:
  typesence-data:
