version: "3.9"
services:
  db1:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1430:1433"
    networks:
      - db1
networks:
  db1:
    driver: bridge
